const reelsData = [
  {
    id: '1',
    username: 'naturelover',
    caption: 'Relaxing waterfall vibes 🌊🌿',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    likes: 320,
    comments: 54,
    shares: 22,
  },
  {
    id: '2',
    username: 'dancerlife',
    caption: 'Freestyle Friday 🔥',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4',
    likes: 880,
    comments: 143,
    shares: 70,
  },
  {
    id: '3',
    username: 'foodie',
    caption: 'Making the perfect burger 🍔',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-10s.mp4',
    likes: 512,
    comments: 89,
    shares: 36,
  },
  {
    id: '4',
    username: 'petworld',
    caption: 'Puppy being adorable 🐶',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    likes: 1340,
    comments: 205,
    shares: 99,
  },
  {
    id: '5',
    username: 'skaterguy',
    caption: 'Skating through the city 🛹',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-15s.mp4',
    likes: 942,
    comments: 101,
    shares: 48,
  },
  {
    id: '6',
    username: 'traveldiaries',
    caption: 'Sunrise in the mountains 🏞️',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-20s.mp4',
    likes: 723,
    comments: 76,
    shares: 34,
  },
  {
    id: '7',
    username: 'artistcorner',
    caption: 'Sketching live ✏️',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-30s.mp4',
    likes: 410,
    comments: 45,
    shares: 19,
  },
  {
    id: '8',
    username: 'gymmotivation',
    caption: 'No pain no gain 💪',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-12s.mp4',
    likes: 1032,
    comments: 134,
    shares: 52,
  },
  {
    id: '9',
    username: 'fashionista',
    caption: 'OOTD vibes 👗✨',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-7s.mp4',
    likes: 865,
    comments: 67,
    shares: 41,
  },
  {
    id: '10',
    username: 'coderlife',
    caption: 'This is how I debug 👨‍💻',
    videoUrl: 'https://samplelib.com/lib/preview/mp4/sample-9s.mp4',
    likes: 777,
    comments: 88,
    shares: 35,
  },
];

export default reelsData;
